// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokRichtext, StoryblokMultilink } from '../storyblok.d.ts';
export interface About {
  content?: (AssetBlok | Gallery | GalleryText | SimpleLink | TextAsset)[];
  component: "About";
  _uid: string;
  [k: string]: unknown;
}

export interface AssetBlok {
  asset: StoryblokAsset;
  component: "AssetBlok";
  _uid: string;
  [k: string]: unknown;
}

export interface Case {
  coverAsset: AssetBlok[];
  title: string;
  projectYear: string;
  services: (number | string)[];
  body?: (AssetBlok | Gallery | GalleryText | SimpleLink | TextAsset)[];
  cubeCover: StoryblokAsset;
  component: "Case";
  _uid: string;
  [k: string]: unknown;
}

export interface CaseOverview {
  cases: (ISbStoryData<Case> | string)[];
  component: "CaseOverview";
  _uid: string;
  [k: string]: unknown;
}

export interface Contact {
  title: string;
  subtitle: string;
  placeholders?: unknown;
  placeholderName: string;
  placeholderCompany: string;
  placeholderEmail: string;
  placeholderServices: string;
  placeholderMessage: string;
  submitButtonLabel: string;
  component: "Contact";
  _uid: string;
  [k: string]: unknown;
}

export interface DropdownInput {
  placeholder: string;
  component: "DropdownInput";
  _uid: string;
  [k: string]: unknown;
}

export interface Gallery {
  headline?: string;
  media: AssetBlok[];
  component: "Gallery";
  _uid: string;
  [k: string]: unknown;
}

export interface GalleryText {
  media: AssetBlok[];
  headline?: string;
  text?: StoryblokRichtext;
  alignMedia?: "" | "alignLeft" | "alignRight";
  component: "GalleryText";
  _uid: string;
  [k: string]: unknown;
}

export interface Homepage {
  component: "Homepage";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | About
    | AssetBlok
    | Case
    | CaseOverview
    | Contact
    | DropdownInput
    | Gallery
    | GalleryText
    | Homepage
    | Page
    | Richtext
    | Settings
    | SimpleHeadline
    | SimpleLink
    | TextareaInput
    | TextAsset
    | TextInput
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Richtext {
  richtext: StoryblokRichtext;
  component: "richtext";
  _uid: string;
  [k: string]: unknown;
}

export interface Settings {
  headerLogo: StoryblokAsset;
  headerContactButtonLabel: string;
  headerNav: SimpleLink[];
  footerContactHeadline: string;
  footerContactTagline: string;
  footerContactButtonLabel: string;
  footerLogo: StoryblokAsset;
  footerTagline: string;
  footerSocials?: SimpleLink[];
  footerPhone?: string;
  footerCopywrite: string;
  component: "Settings";
  _uid: string;
  [k: string]: unknown;
}

export interface SimpleHeadline {
  component: "SimpleHeadline";
  _uid: string;
  [k: string]: unknown;
}

export interface SimpleLink {
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  linkText: string;
  thumbnail?: StoryblokAsset;
  linkTagline?: string;
  component: "SimpleLink";
  _uid: string;
  [k: string]: unknown;
}

export interface TextareaInput {
  placeholder: string;
  component: "TextareaInput";
  _uid: string;
  [k: string]: unknown;
}

export interface TextAsset {
  title?: string;
  richtext: StoryblokRichtext;
  asset: AssetBlok[];
  alignAsset?: "alignLeft" | "alignRight";
  component: "TextAsset";
  _uid: string;
  [k: string]: unknown;
}

export interface TextInput {
  type: "text" | "email";
  placeholder: string;
  component: "TextInput";
  _uid: string;
  [k: string]: unknown;
}
