// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext } from '../storyblok.d.ts';
export interface AssetBlok {
  asset: StoryblokAsset;
  component: "AssetBlok";
  _uid: string;
  [k: string]: unknown;
}

export interface Case {
  coverAsset: AssetBlok[];
  title: string;
  projectYear: string;
  services: (number | string)[];
  introText: StoryblokRichtext;
  body?: (AssetBlok | ContactForm | SimpleLink | TextAsset)[];
  cubeCover: StoryblokAsset;
  component: "Case";
  _uid: string;
  [k: string]: unknown;
}

export interface CaseOverview {
  introText?: string;
  cases: (ISbStoryData<Case> | string)[];
  component: "CaseOverview";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactForm {
  title: string;
  subtitle: string;
  placeholders?: unknown;
  placeholderName: string;
  placeholderCompany: string;
  placeholderEmail: string;
  placeholderServices: string;
  placeholderMessage: string;
  submitButtonLabel: string;
  component: "ContactForm";
  _uid: string;
  [k: string]: unknown;
}

export interface DropdownInput {
  placeholder: string;
  component: "DropdownInput";
  _uid: string;
  [k: string]: unknown;
}

export interface Homepage {
  component: "Homepage";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | AssetBlok
    | Case
    | CaseOverview
    | ContactForm
    | DropdownInput
    | Homepage
    | Page
    | Settings
    | SimpleHeadline
    | SimpleLink
    | TextareaInput
    | TextAsset
    | TextInput
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Settings {
  navLogo: StoryblokAsset;
  menu: SimpleLink[];
  component: "Settings";
  _uid: string;
  [k: string]: unknown;
}

export interface SimpleHeadline {
  component: "SimpleHeadline";
  _uid: string;
  [k: string]: unknown;
}

export interface SimpleLink {
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  linktText: string;
  thumbnail?: StoryblokAsset;
  linkTagline?: string;
  component: "SimpleLink";
  _uid: string;
  [k: string]: unknown;
}

export interface TextareaInput {
  placeholder: string;
  component: "TextareaInput";
  _uid: string;
  [k: string]: unknown;
}

export interface TextAsset {
  title?: string;
  richtext?: StoryblokRichtext;
  asset: AssetBlok[];
  alignAsset?: "alignLeft" | "alignRight";
  component: "TextAsset";
  _uid: string;
  [k: string]: unknown;
}

export interface TextInput {
  type: "text" | "email";
  placeholder: string;
  component: "TextInput";
  _uid: string;
  [k: string]: unknown;
}
