// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokRichtext, StoryblokAsset, StoryblokMultiasset } from '../storyblok.d.ts';
export interface Case {
  title?: string;
  introText?: StoryblokRichtext;
  coverImage?: StoryblokAsset;
  assetGallery?: StoryblokMultiasset;
  body?: (Case | CaseOverview | Page)[];
  industry?: {
    [k: string]: unknown;
  }[];
  component: "Case";
  _uid: string;
  [k: string]: unknown;
}

export interface CaseOverview {
  cases: (ISbStoryData<Case> | string)[];
  component: "CaseOverview";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Case | CaseOverview | Page)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Case | CaseOverview | Page;
